import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const udevGothic35JPDOC = localFont({
	src: "./fonts/UDEVGothic35JPDOC-Regular.ttf",
	variable: "--font-udev-gothic-35-jp-doc",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${udevGothic35JPDOC.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
